Repository managarm/managarm, pull requests merged in 2023-10, with the labels that each got.

#548 virtio-gpu driver rework
  drivers/gfx/virtio/meson.build
  drivers/gfx/virtio/src/commands.cpp
  drivers/gfx/virtio/src/commands.hpp
  drivers/gfx/virtio/src/main.cpp
  drivers/gfx/virtio/src/spec.hpp
  drivers/gfx/virtio/src/virtio.hpp
Labels: performance, high impact

#590 Sysfs seeking improvements
  posix/subsystem/src/file.cpp
  posix/subsystem/src/sysfs.cpp
  posix/subsystem/src/sysfs.hpp
  protocols/fs/src/server.cpp
Labels: enhancement, bugfix

#585 Implement USB sysfs support
  drivers/gfx/bochs/src/main.cpp
  drivers/gfx/plainfb/src/main.cpp
  drivers/gfx/virtio/src/main.cpp
  drivers/gfx/vmware/src/main.cpp
  drivers/uart/src/main.cpp
  drivers/usb/devices/hid/src/hid.hpp
  drivers/usb/devices/hid/src/main.cpp
  drivers/usb/devices/hid/src/spec.hpp
  drivers/usb/devices/storage/src/main.cpp
  drivers/usb/devices/storage/src/storage.hpp
  drivers/usb/hcds/ehci/src/ehci.hpp
  drivers/usb/hcds/ehci/src/main.cpp
  drivers/usb/hcds/uhci/src/main.cpp
  drivers/usb/hcds/uhci/src/schedule.hpp
  drivers/usb/hcds/xhci/src/main.cpp
  drivers/usb/hcds/xhci/src/trb.hpp
  drivers/usb/hcds/xhci/src/xhci.hpp
  posix/subsystem/meson.build
  posix/subsystem/src/main.cpp
  posix/subsystem/src/subsystem/generic.cpp
  posix/subsystem/src/subsystem/usb/attributes.cpp
  posix/subsystem/src/subsystem/usb/attributes.hpp
  posix/subsystem/src/subsystem/usb/devices.hpp
  posix/subsystem/src/subsystem/usb/root-hub.hpp
  posix/subsystem/src/subsystem/usb/usb.cpp
  posix/subsystem/src/subsystem/usb/usb.hpp
  protocols/usb/include/protocols/usb/api.hpp
  protocols/usb/include/protocols/usb/client.hpp
  protocols/usb/include/protocols/usb/hub.hpp
  protocols/usb/include/protocols/usb/server.hpp
  protocols/usb/include/protocols/usb/usb.hpp
  protocols/usb/src/api.cpp
  protocols/usb/src/client.cpp
  protocols/usb/src/hub.cpp
  protocols/usb/src/server.cpp
  protocols/usb/usb.bragi
Labels: enhancement, high impact
